version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-hello-manual"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1wz90rymt8vds"
s3_prefix = "sam-hello-manual"
region = "ap-southeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
